version: "3"
services:
   db:
     image: postgres:13.0-alpine
     restart: always
     environment:
       POSTGRES_PASSWORD: oxefood
       POSTGRES_DB: oxefood
     ports:
       - 5435:5432
     volumes:
       - postgres-data:/bitnami/postgresql/data

volumes:
    postgres-data:
